// <auto-generated />
using System;
using HukukGorev.Persistance.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HukukGorev.Persistance.Migrations
{
    [DbContext(typeof(HukukGorevDbContext))]
    [Migration("20260225134648_ProjeTabloları")]
    partial class ProjeTabloları
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HukukGorev.Domain.Entities.AltGorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACIKLAMA");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit")
                        .HasColumnName("AKTIF");

                    b.Property<int?>("AtananKullaniciId")
                        .HasColumnType("int")
                        .HasColumnName("ATANANKULLANICIID");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("BASLIK");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATEDAT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CREATEDBY");

                    b.Property<int>("Durum")
                        .HasColumnType("int")
                        .HasColumnName("DURUM");

                    b.Property<int>("GorevId")
                        .HasColumnType("int")
                        .HasColumnName("GOREVID");

                    b.Property<DateTime?>("TahminibitisTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("TAHMINIBITISTARIHI");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("TAMAMLANMATARIHI");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATEDAT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UPDATEDBY");

                    b.HasKey("Id");

                    b.HasIndex("AtananKullaniciId");

                    b.HasIndex("GorevId");

                    b.ToTable("ALT_GOREVLER", (string)null);
                });

            modelBuilder.Entity("HukukGorev.Domain.Entities.Ayar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACIKLAMA");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit")
                        .HasColumnName("AKTIF");

                    b.Property<string>("Anahtar")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ANAHTAR");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DEGER");

                    b.HasKey("Id");

                    b.HasIndex("Anahtar")
                        .IsUnique();

                    b.ToTable("AYARLAR", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Maksimum dosya boyutu (MB)",
                            Aktif = true,
                            Anahtar = "MaxDosyaBoyutuMB",
                            Deger = "25"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Görev süresinin ortasında hatırlatma (oran)",
                            Aktif = true,
                            Anahtar = "HatirlatmaOrtasiGun",
                            Deger = "0.5"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Bitiş tarihinden kaç gün önce hatırlatma",
                            Aktif = true,
                            Anahtar = "HatirlatmaBitimGun",
                            Deger = "1"
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "SMTP sunucu adresi",
                            Aktif = true,
                            Anahtar = "SmtpHost",
                            Deger = "smtp.example.com"
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "SMTP port numarası",
                            Aktif = true,
                            Anahtar = "SmtpPort",
                            Deger = "587"
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "SMTP kullanıcı adı",
                            Aktif = true,
                            Anahtar = "SmtpKullaniciAdi",
                            Deger = ""
                        },
                        new
                        {
                            Id = 7,
                            Aciklama = "SMTP şifre",
                            Aktif = true,
                            Anahtar = "SmtpSifre",
                            Deger = ""
                        });
                });

            modelBuilder.Entity("HukukGorev.Domain.Entities.Bildirim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit")
                        .HasColumnName("AKTIF");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("BASLIK");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATEDAT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CREATEDBY");

                    b.Property<int?>("GorevId")
                        .HasColumnType("int")
                        .HasColumnName("GOREVID");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int")
                        .HasColumnName("KULLANICIID");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("MESAJ");

                    b.Property<bool>("Okundu")
                        .HasColumnType("bit")
                        .HasColumnName("OKUNDU");

                    b.Property<int>("Tip")
                        .HasColumnType("int")
                        .HasColumnName("TIP");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATEDAT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UPDATEDBY");

                    b.HasKey("Id");

                    b.HasIndex("GorevId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("BILDIRIMLER", (string)null);
                });

            modelBuilder.Entity("HukukGorev.Domain.Entities.Etiket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("AD");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit")
                        .HasColumnName("AKTIF");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATEDAT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CREATEDBY");

                    b.Property<string>("Renk")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("RENK");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATEDAT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UPDATEDBY");

                    b.HasKey("Id");

                    b.ToTable("ETIKETLER", (string)null);
                });

            modelBuilder.Entity("HukukGorev.Domain.Entities.Gorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACIKLAMA");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit")
                        .HasColumnName("AKTIF");

                    b.Property<int>("AtamaTipi")
                        .HasColumnType("int")
                        .HasColumnName("ATAMATIPI");

                    b.Property<int?>("AtananGrupId")
                        .HasColumnType("int")
                        .HasColumnName("ATANANGRUPID");

                    b.Property<int?>("AtananKullaniciId")
                        .HasColumnType("int")
                        .HasColumnName("ATANANKULLANICIID");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("BASLIK");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("BITISTARIHI");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATEDAT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CREATEDBY");

                    b.Property<int>("Durum")
                        .HasColumnType("int")
                        .HasColumnName("DURUM");

                    b.Property<int?>("GorevTipiId")
                        .HasColumnType("int")
                        .HasColumnName("GOREVTIPIID");

                    b.Property<bool>("HatirlatmaGonderildiBitimi")
                        .HasColumnType("bit")
                        .HasColumnName("HATIRLATMAGONDERILDIBITIMI");

                    b.Property<bool>("HatirlatmaGonderildiOrtasi")
                        .HasColumnType("bit")
                        .HasColumnName("HATIRLATMAGONDERILDIORTASI");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int")
                        .HasColumnName("OLUSTURANKULLANICIID");

                    b.Property<int>("Oncelik")
                        .HasColumnType("int")
                        .HasColumnName("ONCELIK");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("TAMAMLANMATARIHI");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATEDAT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UPDATEDBY");

                    b.Property<int?>("UzerineAlanKullaniciId")
                        .HasColumnType("int")
                        .HasColumnName("UZERINEALANKULLANICIID");

                    b.HasKey("Id");

                    b.HasIndex("AtananGrupId");

                    b.HasIndex("AtananKullaniciId");

                    b.HasIndex("GorevTipiId");

                    b.HasIndex("OlusturanKullaniciId");

                    b.HasIndex("UzerineAlanKullaniciId");

                    b.ToTable("GOREVLER", (string)null);
                });

            modelBuilder.Entity("HukukGorev.Domain.Entities.GorevAtamaLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACIKLAMA");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit")
                        .HasColumnName("AKTIF");

                    b.Property<int?>("AltGorevId")
                        .HasColumnType("int")
                        .HasColumnName("ALTGOREVID");

                    b.Property<DateTime>("AtamaTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("ATAMATARIHI");

                    b.Property<int>("AtamaTipi")
                        .HasColumnType("int")
                        .HasColumnName("ATAMATIPI");

                    b.Property<int?>("AtananGrupId")
                        .HasColumnType("int")
                        .HasColumnName("ATANANGRUPID");

                    b.Property<int?>("AtananKullaniciId")
                        .HasColumnType("int")
                        .HasColumnName("ATANANKULLANICIID");

                    b.Property<int>("AtayanKullaniciId")
                        .HasColumnType("int")
                        .HasColumnName("ATAYANKULLANICIID");

                    b.Property<int?>("GorevId")
                        .HasColumnType("int")
                        .HasColumnName("GOREVID");

                    b.HasKey("Id");

                    b.HasIndex("AltGorevId");

                    b.HasIndex("AtananGrupId");

                    b.HasIndex("AtananKullaniciId");

                    b.HasIndex("AtayanKullaniciId");

                    b.HasIndex("GorevId");

                    b.ToTable("GOREV_ATAMA_LOGLARI", (string)null);
                });

            modelBuilder.Entity("HukukGorev.Domain.Entities.GorevDosya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit")
                        .HasColumnName("AKTIF");

                    b.Property<int?>("AltGorevId")
                        .HasColumnType("int")
                        .HasColumnName("ALTGOREVID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATEDAT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CREATEDBY");

                    b.Property<string>("DosyaAdi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DOSYAADI");

                    b.Property<long>("DosyaBoyutu")
                        .HasColumnType("bigint")
                        .HasColumnName("DOSYABOYUTU");

                    b.Property<byte[]>("DosyaIcerigi")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("DOSYAICERIGI");

                    b.Property<string>("DosyaTipi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DOSYATIPI");

                    b.Property<int?>("GorevId")
                        .HasColumnType("int")
                        .HasColumnName("GOREVID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATEDAT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UPDATEDBY");

                    b.HasKey("Id");

                    b.HasIndex("AltGorevId");

                    b.HasIndex("GorevId");

                    b.ToTable("GOREV_DOSYALARI", (string)null);
                });

            modelBuilder.Entity("HukukGorev.Domain.Entities.GorevEtiket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit")
                        .HasColumnName("AKTIF");

                    b.Property<int>("EtiketId")
                        .HasColumnType("int")
                        .HasColumnName("ETIKETID");

                    b.Property<int>("GorevId")
                        .HasColumnType("int")
                        .HasColumnName("GOREVID");

                    b.HasKey("Id");

                    b.HasIndex("EtiketId");

                    b.HasIndex("GorevId");

                    b.ToTable("GOREV_ETIKETLERI", (string)null);
                });

            modelBuilder.Entity("HukukGorev.Domain.Entities.GorevTipi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACIKLAMA");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("AD");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit")
                        .HasColumnName("AKTIF");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATEDAT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATEDAT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UPDATEDBY");

                    b.HasKey("Id");

                    b.ToTable("GOREV_TIPLERI", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Proje görevi",
                            Ad = "Proje",
                            Aktif = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Sözleşme görevi",
                            Ad = "Sözleşme",
                            Aktif = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "KVKK görevi",
                            Ad = "KVKK",
                            Aktif = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Danışmanlık görevi",
                            Ad = "Danışmanlık",
                            Aktif = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "Personel görevi",
                            Ad = "Personel",
                            Aktif = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HukukGorev.Domain.Entities.GorevYorum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit")
                        .HasColumnName("AKTIF");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATEDAT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CREATEDBY");

                    b.Property<int>("GorevId")
                        .HasColumnType("int")
                        .HasColumnName("GOREVID");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ICERIK");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int")
                        .HasColumnName("KULLANICIID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATEDAT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UPDATEDBY");

                    b.HasKey("Id");

                    b.HasIndex("GorevId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("GOREV_YORUMLARI", (string)null);
                });

            modelBuilder.Entity("HukukGorev.Domain.Entities.Grup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACIKLAMA");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("AD");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit")
                        .HasColumnName("AKTIF");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATEDAT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATEDAT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UPDATEDBY");

                    b.HasKey("Id");

                    b.ToTable("GRUPLAR", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Uyum Grubu",
                            Ad = "Uyum",
                            Aktif = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "KVKK Grubu",
                            Ad = "KVKK",
                            Aktif = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HukukGorev.Domain.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("AD");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit")
                        .HasColumnName("AKTIF");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATEDAT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CREATEDBY");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("EMAIL");

                    b.Property<int>("Rol")
                        .HasColumnType("int")
                        .HasColumnName("ROL");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SIFREHASH");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SOYAD");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATEDAT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UPDATEDBY");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("KULLANICILAR", (string)null);
                });

            modelBuilder.Entity("HukukGorev.Domain.Entities.KullaniciGrup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit")
                        .HasColumnName("AKTIF");

                    b.Property<int>("GrupId")
                        .HasColumnType("int")
                        .HasColumnName("GRUPID");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int")
                        .HasColumnName("KULLANICIID");

                    b.HasKey("Id");

                    b.HasIndex("GrupId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("KULLANICI_GRUPLARI", (string)null);
                });

            modelBuilder.Entity("HukukGorev.Domain.Entities.AltGorev", b =>
                {
                    b.HasOne("HukukGorev.Domain.Entities.Kullanici", "AtananKullanici")
                        .WithMany()
                        .HasForeignKey("AtananKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HukukGorev.Domain.Entities.Gorev", "Gorev")
                        .WithMany("AltGorevler")
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtananKullanici");

                    b.Navigation("Gorev");
                });

            modelBuilder.Entity("HukukGorev.Domain.Entities.Bildirim", b =>
                {
                    b.HasOne("HukukGorev.Domain.Entities.Gorev", "Gorev")
                        .WithMany()
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HukukGorev.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("Bildirimler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gorev");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("HukukGorev.Domain.Entities.Gorev", b =>
                {
                    b.HasOne("HukukGorev.Domain.Entities.Grup", "AtananGrup")
                        .WithMany("Gorevler")
                        .HasForeignKey("AtananGrupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HukukGorev.Domain.Entities.Kullanici", "AtananKullanici")
                        .WithMany("AtananGorevler")
                        .HasForeignKey("AtananKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HukukGorev.Domain.Entities.GorevTipi", "GorevTipi")
                        .WithMany("Gorevler")
                        .HasForeignKey("GorevTipiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HukukGorev.Domain.Entities.Kullanici", "OlusturanKullanici")
                        .WithMany("OlusturulanGorevler")
                        .HasForeignKey("OlusturanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HukukGorev.Domain.Entities.Kullanici", "UzerineAlanKullanici")
                        .WithMany()
                        .HasForeignKey("UzerineAlanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AtananGrup");

                    b.Navigation("AtananKullanici");

                    b.Navigation("GorevTipi");

                    b.Navigation("OlusturanKullanici");

                    b.Navigation("UzerineAlanKullanici");
                });

            modelBuilder.Entity("HukukGorev.Domain.Entities.GorevAtamaLog", b =>
                {
                    b.HasOne("HukukGorev.Domain.Entities.AltGorev", "AltGorev")
                        .WithMany("AtamaLoglari")
                        .HasForeignKey("AltGorevId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HukukGorev.Domain.Entities.Grup", "AtananGrup")
                        .WithMany()
                        .HasForeignKey("AtananGrupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HukukGorev.Domain.Entities.Kullanici", "AtananKullanici")
                        .WithMany()
                        .HasForeignKey("AtananKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HukukGorev.Domain.Entities.Kullanici", "AtayanKullanici")
                        .WithMany("AtamaLoglari")
                        .HasForeignKey("AtayanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HukukGorev.Domain.Entities.Gorev", "Gorev")
                        .WithMany("AtamaLoglari")
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AltGorev");

                    b.Navigation("AtananGrup");

                    b.Navigation("AtananKullanici");

                    b.Navigation("AtayanKullanici");

                    b.Navigation("Gorev");
                });

            modelBuilder.Entity("HukukGorev.Domain.Entities.GorevDosya", b =>
                {
                    b.HasOne("HukukGorev.Domain.Entities.AltGorev", "AltGorev")
                        .WithMany("Dosyalar")
                        .HasForeignKey("AltGorevId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HukukGorev.Domain.Entities.Gorev", "Gorev")
                        .WithMany("Dosyalar")
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AltGorev");

                    b.Navigation("Gorev");
                });

            modelBuilder.Entity("HukukGorev.Domain.Entities.GorevEtiket", b =>
                {
                    b.HasOne("HukukGorev.Domain.Entities.Etiket", "Etiket")
                        .WithMany("GorevEtiketler")
                        .HasForeignKey("EtiketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HukukGorev.Domain.Entities.Gorev", "Gorev")
                        .WithMany("GorevEtiketler")
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etiket");

                    b.Navigation("Gorev");
                });

            modelBuilder.Entity("HukukGorev.Domain.Entities.GorevYorum", b =>
                {
                    b.HasOne("HukukGorev.Domain.Entities.Gorev", "Gorev")
                        .WithMany("Yorumlar")
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HukukGorev.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("Yorumlar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gorev");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("HukukGorev.Domain.Entities.KullaniciGrup", b =>
                {
                    b.HasOne("HukukGorev.Domain.Entities.Grup", "Grup")
                        .WithMany("KullaniciGruplari")
                        .HasForeignKey("GrupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HukukGorev.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("KullaniciGruplari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grup");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("HukukGorev.Domain.Entities.AltGorev", b =>
                {
                    b.Navigation("AtamaLoglari");

                    b.Navigation("Dosyalar");
                });

            modelBuilder.Entity("HukukGorev.Domain.Entities.Etiket", b =>
                {
                    b.Navigation("GorevEtiketler");
                });

            modelBuilder.Entity("HukukGorev.Domain.Entities.Gorev", b =>
                {
                    b.Navigation("AltGorevler");

                    b.Navigation("AtamaLoglari");

                    b.Navigation("Dosyalar");

                    b.Navigation("GorevEtiketler");

                    b.Navigation("Yorumlar");
                });

            modelBuilder.Entity("HukukGorev.Domain.Entities.GorevTipi", b =>
                {
                    b.Navigation("Gorevler");
                });

            modelBuilder.Entity("HukukGorev.Domain.Entities.Grup", b =>
                {
                    b.Navigation("Gorevler");

                    b.Navigation("KullaniciGruplari");
                });

            modelBuilder.Entity("HukukGorev.Domain.Entities.Kullanici", b =>
                {
                    b.Navigation("AtamaLoglari");

                    b.Navigation("AtananGorevler");

                    b.Navigation("Bildirimler");

                    b.Navigation("KullaniciGruplari");

                    b.Navigation("OlusturulanGorevler");

                    b.Navigation("Yorumlar");
                });
#pragma warning restore 612, 618
        }
    }
}
